redis:
  enabled: true
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  
  # 连接池配置
  pool:
    max_idle: 10
    max_active: 100
    idle_timeout: "5m"
  
  # 超时配置
  timeout:
    connect: "5s"
    read: "3s"
    write: "3s"
  
  # 日志配置
  logging:
    enabled: true
    level: "info"
    file: "redis.log" 